### ISSUE TITLE
documentation for testing is very sparse

### ISSUE THREAD

**Issue by TovarishFin** [bancorprotocol/contracts_eos#2]
Looking over the contracts, I wanted to try running the tests. When looking at the README, I see only this:
> Tests are included and can be run using fungi.

What is fungi? How do I run the tests?

A bit more information on this subject would be greatly appreciated. Not only for testing the repo itself but also for the EOS community in general to see how tests are run on different projects.

**Comment by TovarishFin** [comment]
I finally found (fungi)[https://github.com/fungi-boxes/fungi]. I spent a few hours looking for this before creating an issue. Perhaps my google-fu is quite weak... but it would still be a good idea to at least put a link to this in the docs.

**Comment by yudilevi** [comment]
Hey,

We're planning to add more documentation in the upcoming weeks - fungi is new and we still need to clean it up a bit.

Will update soon.

**Comment by ricktobacco** [comment]
Hi @TovarishFin 
We welcome you to try out our new tests, they're based on vanilla eosjs2 rather than fungi :)
