### ISSUE TITLE
a few `is_account` is not enforced

### ISSUE THREAD

**Issue by DenisCarriere** [bancorprotocol/contracts_eos#28]
Noticed a few of `is_account` that are "dangling" (`check` not being enforced)

https://github.com/bancorprotocol/contracts_eos/blob/0cb1bd049af6dbd2ae2d8fd6f45a3969ca6947d4/contracts/eos/MultiConverter/MultiConverter.cpp#L87

https://github.com/bancorprotocol/contracts_eos/blob/0cb1bd049af6dbd2ae2d8fd6f45a3969ca6947d4/contracts/eos/MultiConverter/MultiConverter.cpp#L73

**Before**

```c++
is_account(multi_token);
```

**After**

```c++
check( is_account(multi_token), multi_token.to_string() + " account does not exist");
```

**Comment by ricktobacco** [comment]
It's better to use check if you strictly require a custom error message, otherwise is_account by itself will also throw an error that's more generic (the basic behavior we need).
Thank you so much for highlighting this though, we should probably use the check approach.

**Comment by DenisCarriere** [comment]
@ricktobacco I've just tested this locally for myself and `is_account()` only returns a `boolean (true/false)`

It doesn't throw any error

Try adding `is_account("foo"_n);` anywhere in your code and you'll see it won't throw an error

I'm using the latest CDT compiler, maybe things have changed from 1.4 or 1.5 => 1.6

```
$ eosio-cpp --version
eosio-cpp version 1.6.2
```

**Comment by DenisCarriere** [comment]
![image](https://user-images.githubusercontent.com/550895/67803570-b6f92b80-fa63-11e9-8e74-d68e56b85f5d.png)

**Comment by ricktobacco** [comment]
Ah interesting, will update now!

**Comment by yudilevi** [comment]
@ricktobacco are these changes in for all `is_account` checks?

**Comment by ricktobacco** [comment]
@yudilevi Yes

**Comment by yudilevi** [comment]
@ricktobacco awesome, thanks :)
