### ISSUE TITLE
Misleading docs

### ISSUE THREAD

**Issue by Velua** [bancorprotocol/contracts_eos#56]
Docs imply only the contract owner can set a reserve in ```::setreserve```, this should be the converter owner.

https://github.com/bancorprotocol/contracts_eos/blob/dbf07a808a4a564cc95c91bfa2b3ce61138507c1/contracts/eos/BancorConverter/BancorConverter.hpp#L263

It also says one can modify an existing reserve however there isn't logic to handle this and this assertion is made too. 
https://github.com/bancorprotocol/contracts_eos/blob/dbf07a808a4a564cc95c91bfa2b3ce61138507c1/contracts/eos/BancorConverter/BancorConverter.cpp#L184

**Comment by yudilevi** [comment]
@yuval-weiss can you please take a look?
